name: opration
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  very_good_analysis: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.0
  get_it: ^8.2.0
  go_router: ^16.1.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  uuid: ^4.5.1
  fl_chart: ^1.0.0
  icons_launcher: ^3.0.1
  installed_apps: ^1.6.0
  app_usage: ^4.0.1
  permission_handler: ^12.0.1
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.1
  flutter_local_notifications: ^19.4.0
  notification_listener_service: ^0.3.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/image/png/
    - assets/image/svg/
    
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo-Bold.ttf

flutter_assets:
  assets_path: assets/
  output_path: lib/core/theme/
  filename: assets.dart
  field_prefix: 
  ignore_comments: true

icons_launcher:
  image_path: "assets/image/png/app_logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
# dart run icons_launcher:create
# flutter gen-l10n
  