name: opration
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  very_good_analysis: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.0
  get_it: ^8.2.0
  go_router: ^16.1.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  uuid: ^4.5.1
  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/image/png/
    - assets/image/svg/
    
flutter_assets:
  assets_path: assets/
  output_path: lib/core/theme/
  filename: assets.dart
  field_prefix: 
  ignore_comments: true
# flutter gen-l10n